# Generated by Django 3.2.9 on 2022-03-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact number'),
        ),
    ]
